### ISSUE TITLE
Fatal error:  Uncaught Exception: String could not be parsed as XML in C:\xampp\htdocs\chargify\Chargify-PHP-Client\lib\ChargifyConnector.php:158 Stack trace:

### ISSUE THREAD

**Issue by abkiran** [jforrest/Chargify-PHP-Client#21]
Fatal error:  Uncaught Exception: String could not be parsed as XML in C:\xampp\htdocs\chargify\Chargify-PHP-Client\lib\ChargifyConnector.php:158
Stack trace:
#0 C:\xampp\htdocs\chargify\Chargify-PHP-Client\lib\ChargifyConnector.php(158): SimpleXMLElement->__construct('')
#1 C:\xampp\htdocs\chargify\Chargify-PHP-Client\lib\ChargifyCustomer.php(43): ChargifyConnector->createCustomer(Object(ChargifyCustomer))
#2 C:\xampp\htdocs\chargify\customers.php(25): ChargifyCustomer->create()
#3 {main}
  thrown in C:\xampp\htdocs\chargify\Chargify-PHP-Client\lib\ChargifyConnector.php on line 158

**Comment by abkiran** [comment]
stdClass Object
(
[response] => HTTP Basic: Access denied.

[code] => 401
[meta] => Array

Check your access first.
